name: CI

env:
    CI: true
    DB_CONNECTION: ${{ secrets.DB_CONNECTION }}
    DB_HOST: ${{ secrets.DB_HOST }}
    DB_PORT: ${{ secrets.DB_PORT }}
    DB_DATABASE: ${{ secrets.DB_DATABASE }}
    DB_USERNAME: ${{ secrets.DB_USERNAME }}
    DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
    JWT_TABLE: ${{ secrets.JWT_TABLE }}
    JWT_LOGIN: ${{ secrets.JWT_LOGIN }}
    JWT_TTL: ${{ secrets.JWT_TTL }}
    JWT_SECRET: ${{ secrets.JWT_SECRET }}

on:
    workflow_dispatch:
    push:
        tags:
            - 'v*'
            - '[0-9]*'

jobs:
    build-test:
        strategy:
            max-parallel: 9
            fail-fast: true
            matrix:
                operating-system: ['ubuntu-latest', 'macos-latest', 'windows-latest']
                php-versions: ['7.4', '8.0', '8.1', '8.2', '8.3']

        runs-on: ${{ matrix.operating-system }}

        name: ${{ matrix.operating-system }} (PHP ${{ matrix.php-versions }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install libraries
              run: |
                  if [ "$RUNNER_OS" == "Linux" ]; then
                  	   sudo apt-get update
                       sudo apt-get install -y coreutils
                  elif [ "$RUNNER_OS" == "macOS" ]; then
                       brew install coreutils
                  elif [ "$RUNNER_OS" == "Windows" ]; then
                       choco install busybox -y
                  fi
              shell: bash

            - name: Install PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '${{ matrix.php-versions }}'
                  extensions: fileinfo, mysqli, xdebug, mbstring, xmlrpc, gd, intl, xml, zip, soap, bcmath, imap, opcache, pgsql, pdo, imagick
                  tools: composer, phpunit

            - name: Install MySQL
              uses: shogo82148/actions-setup-mysql@v1
              with:
                  mysql-version: '8.0'
                  root-password: 'root'

            - name: Create Database
              run: mysql -u root -proot -e "CREATE DATABASE IF NOT EXISTS simpleauth;"
              shell: bash

            - name: Install Composer
              run: composer install --no-interaction

            - name: Create .env file if needed
              run: |
                  cat > .env << EOF
                  DB_CONNECTION=${{ secrets.DB_CONNECTION }}
                  DB_HOST=${{ secrets.DB_HOST }}
                  DB_PORT=${{ secrets.DB_PORT }}
                  DB_DATABASE=${{ secrets.DB_DATABASE }}
                  DB_USERNAME=${{ secrets.DB_USERNAME }}
                  DB_PASSWORD=${{ secrets.DB_PASSWORD }}
                  JWT_TABLE=${{ secrets.JWT_TABLE }}
                  JWT_LOGIN=${{ secrets.JWT_LOGIN }}
                  JWT_TTL=${{ secrets.JWT_TTL }}
                  JWT_SECRET=${{ secrets.JWT_SECRET }}
                  EOF
              shell: bash

            - name: Start PHP Server
              run: php -S localhost:8000 -t auth > /tmp/php-server.log 2>&1 &
              shell: bash

            - name: PHP Tests
              run: ./vendor/bin/phpunit
